CREATE DATABASE MEDICINEORGANIZER;
CREATE TABLE PACIENTE (
	NOME VARCHAR(90) NOT NULL ,
	CPF VARCHAR(11) NOT NULL,
	CONSTRAINT PACIENTE_PK PRIMARY KEY (CPF) 
);
CREATE TABLE REMEDIO (
	DESCRICAO VARCHAR(90) NOT NULL,
	CODIGO INT NOT NULL,
	CONSTRAINT REMEDIO_PK PRIMARY KEY (CODIGO)
);

CREATE TABLE ENFERMEIRO(
	NOME VARCHAR(90) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	CONSTRAINT ENFERMEIRO_PK PRIMARY KEY (CPF)
);
CREATE TABLE ALERGIA (
	NOME VARCHAR(90) NOT NULL,
	CODIGO INT NOT NULL,
	CONSTRAINT ALERGIA_PK PRIMARY KEY (CODIGO)
);
CREATE TABLE TIPOREMEDIO(
	CODIGO INT NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	CONSTRAINT TIPOREMEDIO_PK PRIMARY KEY (CODIGO)
);
CREATE TABLE ALERGIAPACIENTE(
	PACIENTECPF VARCHAR(11) NOT NULL,
	CODIGOALERGIA INT NOT NULL,
	CONSTRAINT ALERGIAPACIENTE_PK PRIMARY KEY (PACIENTECPF, CODIGOALERGIA),
	FOREIGN KEY (PACIENTECPF) REFERENCES PACIENTE (CPF),
	FOREIGN KEY (CODIGOALERGIA) REFERENCES ALERGIA (CODIGO)
);
CREATE TABLE DOSAGEM(
	CODIGO INT NOT NULL PRIMARY KEY,
	CODIGOREMEDIO INT NOT NULL,
	DOSAGEM DECIMAL(10,2) NOT NULL,
	IDADE INT NOT NULL,
	FOREIGN KEY (CODIGOREMEDIO) REFERENCES REMEDIO (CODIGO)
);
CREATE TABLE CATEGORIAREMEDIO(
	CODIGOREMEDIO INT NOT NULL,
	CODIGOCATEGORIA INT NOT NULL,
	CONSTRAINT CATEGORIAREMEDIO_PK PRIMARY KEY (CODIGOREMEDIO, CODIGOCATEGORIA),
	FOREIGN KEY (CODIGOREMEDIO) REFERENCES REMEDIO (CODIGO),
	FOREIGN KEY (CODIGOCATEGORIA) REFERENCES TIPOREMEDIO (CODIGO)
);
CREATE TABLE AGENDAMENTO(
	CPFENFERMEIRO VARCHAR(11) NOT NULL,
	CPFPACIENTE VARCHAR(11) NOT NULL,
	CODIGOREMEDIO INT NOT NULL,
	CONSTRAINT AGENDAMENTO_PK PRIMARY KEY (CPFENFERMEIRO, CPFPACIENTE, CODIGOREMEDIO),
	FOREIGN KEY (CPFENFERMEIRO) REFERENCES ENFERMEIRO (CPF),
	FOREIGN KEY (CPFPACIENTE) REFERENCES PACIENTE (CPF),
	FOREIGN KEY (CODIGOREMEDIO) REFERENCES REMEDIO (CODIGO)
);




